### ISSUE TITLE
FSReqCallback.oncomplete(fs.js:160:23)

### ISSUE THREAD

**Issue by davidwozabal** [Alamantus/GooglePhotosExportOrganizer#8] opened 2021-06-04 06:25 UTC
In step 3 (organize folders with re-insert exif enabled), I get the following error:

![error](https://user-images.githubusercontent.com/5129411/120753669-d4c62680-c50b-11eb-8506-be017adc8f1a.png)

Also in the second step, some of the zip files do not seem to extract correctly: The check mark does not appear and there is an exclamation mark next to the progress bar (which is but fully filled). However, it is possible to proceed to the next step.

**Comment by Alamantus** [comment] 2021-06-04 19:57
The error message referenced here is a duplicate of #6. I'm working on a new bug fix release today that should handle that error.

As for the second step, I'll have to look into that. Can you tell me how large your zip files are and how many you are trying to extract? Are the files getting _mostly_ extracted, or is the output folder empty?

**Comment by Alamantus** [comment] 2021-06-10 17:42
This error should be fixed in the new [version 1.1.1 release](https://github.com/Alamantus/GooglePhotosExportOrganizer/releases/tag/v1.1.1). Please let me know if you still keep getting the error!

I'll look into the other problem when I get a chance, but in the meantime, can you tell me how large your zip files are and how many you are trying to extract? Are the files getting mostly extracted, or is the output folder empty?

**Comment by Alamantus** [comment] 2021-07-21 17:55
@davidwozabal The main problem in this issue has been resolved. The problem of the zip files apparently not completing is being addressed in Issue #9. If you are still having this problem, please see the [last comment](https://github.com/Alamantus/GooglePhotosExportOrganizer/issues/9#issuecomment-884376643) asking to download a debug version of the app to report any errors displayed.

**Closed** 2021-07-21 17:55 UTC
